NEWS_SOURCES = [
    {
        "key": "reuters_energy",
        "name": "Reuters Energy",
        "url": "https://www.reuters.com/business/energy/",
        "language": "en",
        "country": "Global",
        "coverage": ["global_power", "europe_power", "us_power"],
        "credibility_rating": 98,
        "credibility_label": "Tier 1 wire",
        "notes": "Global wire with strong market coverage and fast operational reporting.",
    },
    {
        "key": "bloomberg_energy",
        "name": "Bloomberg Energy",
        "url": "https://www.bloomberg.com/energy",
        "language": "en",
        "country": "Global",
        "coverage": ["global_power", "commodities", "europe_power"],
        "credibility_rating": 96,
        "credibility_label": "Tier 1 financial",
        "notes": "Institutional-grade markets coverage with strong commodities context.",
    },
    {
        "key": "ft_energy_source",
        "name": "Financial Times Energy Source",
        "url": "https://www.ft.com/energy-source",
        "language": "en",
        "country": "United Kingdom",
        "coverage": ["global_power", "europe_power", "policy"],
        "credibility_rating": 95,
        "credibility_label": "Tier 1 financial",
        "notes": "Trusted macro, power, and policy analysis for institutional readers.",
    },
    {
        "key": "spglobal_power",
        "name": "S&P Global Commodity Insights",
        "url": "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/electric-power",
        "language": "en",
        "country": "Global",
        "coverage": ["us_power", "europe_power", "commodities"],
        "credibility_rating": 95,
        "credibility_label": "Tier 1 specialist",
        "notes": "Deep power-market reporting with pricing and market structure context.",
    },
    {
        "key": "icis_energy",
        "name": "ICIS Energy",
        "url": "https://www.icis.com/explore/commodities/energy/",
        "language": "en",
        "country": "Global",
        "coverage": ["europe_power", "gas", "commodities"],
        "credibility_rating": 93,
        "credibility_label": "Tier 1 specialist",
        "notes": "Respected specialist source across European power, gas, and trading desks.",
    },
    {
        "key": "argus_power",
        "name": "Argus Media Power",
        "url": "https://www.argusmedia.com/en/commodities/power",
        "language": "en",
        "country": "Global",
        "coverage": ["us_power", "europe_power", "commodities"],
        "credibility_rating": 93,
        "credibility_label": "Tier 1 specialist",
        "notes": "Widely used in commodities markets for pricing and sector intelligence.",
    },
    {
        "key": "montel",
        "name": "Montel",
        "url": "https://montel.energy/products/news",
        "language": "en",
        "country": "Europe",
        "coverage": ["europe_power", "power_trading"],
        "credibility_rating": 92,
        "credibility_label": "Tier 1 specialist",
        "notes": "European power-market specialist used by many traders and analysts.",
    },
    {
        "key": "utility_dive",
        "name": "Utility Dive",
        "url": "https://www.utilitydive.com/topic/power-grid/",
        "language": "en",
        "country": "United States",
        "coverage": ["us_power", "grid", "policy"],
        "credibility_rating": 88,
        "credibility_label": "Tier 2 specialist",
        "notes": "Strong grid and utility reporting with high signal for market structure changes.",
    },
    {
        "key": "power_mag",
        "name": "POWER Magazine",
        "url": "https://www.powermag.com/",
        "language": "en",
        "country": "United States",
        "coverage": ["generation", "grid", "us_power"],
        "credibility_rating": 88,
        "credibility_label": "Tier 2 specialist",
        "notes": "Long-running power industry publication focused on operations and generation.",
    },
    {
        "key": "canary_media",
        "name": "Canary Media",
        "url": "https://www.canarymedia.com/topics/grid",
        "language": "en",
        "country": "United States",
        "coverage": ["grid", "renewables", "policy"],
        "credibility_rating": 86,
        "credibility_label": "Tier 2 specialist",
        "notes": "High-quality clean-energy and grid reporting, useful for transition-linked signals.",
    },
    {
        "key": "rto_insider",
        "name": "RTO Insider",
        "url": "https://www.rtoinsider.com/",
        "language": "en",
        "country": "United States",
        "coverage": ["pjm", "isone", "nyiso", "policy"],
        "credibility_rating": 90,
        "credibility_label": "Tier 1 niche",
        "notes": "Important niche source for U.S. ISO/RTO governance and market rule changes.",
    },
    {
        "key": "eenews",
        "name": "E&E News Energywire",
        "url": "https://www.eenews.net/energywire/",
        "language": "en",
        "country": "United States",
        "coverage": ["energy_policy", "us_power", "regulation"],
        "credibility_rating": 89,
        "credibility_label": "Tier 2 specialist",
        "notes": "Useful for U.S. policy and regulatory moves that affect power markets.",
    },
    {
        "key": "pjm_official",
        "name": "PJM Newsroom",
        "url": "https://pjm.com/newsroom",
        "language": "en",
        "country": "United States",
        "coverage": ["pjm", "operator"],
        "credibility_rating": 99,
        "credibility_label": "Official operator",
        "notes": "Primary source for PJM operations, notices, and market communications.",
    },
    {
        "key": "nyiso_official",
        "name": "NYISO News & Press Releases",
        "url": "https://www.nyiso.com/news-press-releases",
        "language": "en",
        "country": "United States",
        "coverage": ["nyiso", "operator"],
        "credibility_rating": 99,
        "credibility_label": "Official operator",
        "notes": "Primary source for NYISO market and operational announcements.",
    },
    {
        "key": "isone_official",
        "name": "ISO New England Press Releases",
        "url": "https://www.iso-ne.com/about/news/press-releases",
        "language": "en",
        "country": "United States",
        "coverage": ["isone", "operator"],
        "credibility_rating": 99,
        "credibility_label": "Official operator",
        "notes": "Primary source for ISO-NE market operations and system conditions.",
    },
    {
        "key": "ercot_official",
        "name": "ERCOT News Releases",
        "url": "https://www.ercot.com/news/release",
        "language": "en",
        "country": "United States",
        "coverage": ["ercot", "operator"],
        "credibility_rating": 99,
        "credibility_label": "Official operator",
        "notes": "Primary ERCOT operating and market notice source.",
    },
    {
        "key": "neso_official",
        "name": "National Energy System Operator",
        "url": "https://www.neso.energy/news",
        "language": "en",
        "country": "United Kingdom",
        "coverage": ["uk_power", "operator"],
        "credibility_rating": 99,
        "credibility_label": "Official operator",
        "notes": "Primary UK system-operator source for balancing and operational updates.",
    },
    {
        "key": "epex_spot",
        "name": "EPEX SPOT News",
        "url": "https://www.epexspot.com/en/news",
        "language": "en",
        "country": "Europe",
        "coverage": ["europe_power", "exchange"],
        "credibility_rating": 97,
        "credibility_label": "Official exchange",
        "notes": "Primary European power exchange source for market design and exchange updates.",
    },
    {
        "key": "nord_pool",
        "name": "Nord Pool Newsroom",
        "url": "https://www.nordpoolgroup.com/en/newsroom/",
        "language": "en",
        "country": "Nordics",
        "coverage": ["nordics", "exchange"],
        "credibility_rating": 97,
        "credibility_label": "Official exchange",
        "notes": "Primary Nordic power exchange source with market rule and operational signals.",
    },
    {
        "key": "eex",
        "name": "EEX Newsroom",
        "url": "https://www.eex.com/en/about/newsroom",
        "language": "en",
        "country": "Germany",
        "coverage": ["europe_power", "exchange"],
        "credibility_rating": 97,
        "credibility_label": "Official exchange",
        "notes": "Important exchange-level source for European power and derivatives developments.",
    },
    {
        "key": "entsoe",
        "name": "ENTSO-E News",
        "url": "https://www.entsoe.eu/news/",
        "language": "en",
        "country": "Europe",
        "coverage": ["europe_power", "grid", "cross_border"],
        "credibility_rating": 98,
        "credibility_label": "Official grid network",
        "notes": "Pan-European transmission and cross-border coordination source.",
    },
    {
        "key": "acer",
        "name": "ACER News",
        "url": "https://www.acer.europa.eu/news-and-events/news",
        "language": "en",
        "country": "Europe",
        "coverage": ["europe_power", "regulation"],
        "credibility_rating": 98,
        "credibility_label": "Official regulator",
        "notes": "Primary EU regulator source for market oversight and regulatory changes.",
    },
    {
        "key": "ofgem",
        "name": "Ofgem Publications",
        "url": "https://www.ofgem.gov.uk/publications",
        "language": "en",
        "country": "United Kingdom",
        "coverage": ["uk_power", "regulation"],
        "credibility_rating": 98,
        "credibility_label": "Official regulator",
        "notes": "Primary UK energy regulator source.",
    },
    {
        "key": "rte_france",
        "name": "RTE France Actualites",
        "url": "https://www.rte-france.com/actualites",
        "language": "fr",
        "country": "France",
        "coverage": ["france_power", "operator", "cross_border"],
        "credibility_rating": 98,
        "credibility_label": "Official operator",
        "notes": "Primary French grid operator source. Non-English items should be translated in-product.",
    },
    {
        "key": "bundesnetzagentur",
        "name": "Bundesnetzagentur Press",
        "url": "https://www.bundesnetzagentur.de/EN/General/Press/press_node.html",
        "language": "de",
        "country": "Germany",
        "coverage": ["germany_power", "regulation"],
        "credibility_rating": 98,
        "credibility_label": "Official regulator",
        "notes": "Primary German regulator source. Non-English items should be translated in-product.",
    },
    {
        "key": "elia",
        "name": "Elia News",
        "url": "https://www.elia.be/en/news",
        "language": "en",
        "country": "Belgium",
        "coverage": ["belgium_power", "operator", "cross_border"],
        "credibility_rating": 97,
        "credibility_label": "Official operator",
        "notes": "Belgian TSO source useful for continental cross-border and adequacy signals.",
    },
    {
        "key": "terna",
        "name": "Terna Press Releases",
        "url": "https://www.terna.it/en/media/press-releases",
        "language": "en",
        "country": "Italy",
        "coverage": ["italy_power", "operator"],
        "credibility_rating": 97,
        "credibility_label": "Official operator",
        "notes": "Italian TSO source with grid and adequacy updates.",
    },
    {
        "key": "ree",
        "name": "Red Electrica News",
        "url": "https://www.ree.es/en/press-office/news",
        "language": "es",
        "country": "Spain",
        "coverage": ["spain_power", "operator"],
        "credibility_rating": 97,
        "credibility_label": "Official operator",
        "notes": "Spanish system operator source. Non-English items should be translated in-product.",
    },
]

NEWS_SOURCE_MAP = {source["key"]: source for source in NEWS_SOURCES}
